# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20161104_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comp_flf',
            new_name='comp_flg',
        ),
    ]
